# Generated by Django 4.2.11 on 2026-03-13 01:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                ("country_id", models.AutoField(primary_key=True, serialize=False)),
                ("country_name", models.CharField(max_length=128, unique=True)),
                ("country_name_eng", models.CharField(max_length=128, unique=True)),
                ("country_code", models.CharField(max_length=8, unique=True)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="NonSpatialCities",
            fields=[
                ("city_id", models.AutoField(primary_key=True, serialize=False)),
                ("city_name", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("population", models.IntegerField()),
                ("geolocation", models.CharField(max_length=200)),
                ("province", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Cities",
            fields=[
                ("city_id", models.AutoField(primary_key=True, serialize=False)),
                ("city_name", models.CharField(max_length=128, unique=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geowebapis.countries",
                    ),
                ),
            ],
            options={
                "managed": True,
            },
        ),
    ]
