# Generated by Django 5.2 on 2025-06-12 15:22

import uuid
from datetime import datetime
from django.utils import timezone

from django.db import migrations
from django.contrib.gis.geos import GEOSGeometry
from pathlib import Path

import geopandas as gpd
import shapely


def load_fields_polygon_data(apps, schema_editor):
    # import heavy geo libs here to avoid initializing GEOS at module import time

    files_path = ['static/data/farming/spatial/ChampAPolygon.geojson',
                  'static/data/farming/spatial/ChampBPolygon.geojson',
                  'static/data/farming/spatial/ChampCPolygon.geojson'
                  ]

    # Les tables requises pour l'insertion des données spatiales
    SamplingFeatures = apps.get_model('geowebapp', 'SamplingFeatures')
    CV_SamplingFeatureType = apps.get_model(
        'geowebapp', 'CV_SamplingFeatureType')
    CV_SamplingFeatureGeoType = apps.get_model(
        'geowebapp', 'CV_SamplingFeatureGeoType')
    RelatedFeatures = apps.get_model('geowebapp', 'RelatedFeatures')
    CV_RelationshipType = apps.get_model('geowebapp', 'CV_RelationshipType')

    CV_ElevationDatum = apps.get_model('geowebapp', 'CV_ElevationDatum')

    Organizations = apps.get_model('geowebapp', 'Organizations')
    Affiliations = apps.get_model('geowebapp', 'Affiliations')

    Methods = apps.get_model('geowebapp', 'Methods')
    CV_MethodType = apps.get_model('geowebapp', 'CV_MethodType')

    Actions = apps.get_model('geowebapp', 'Actions')
    CV_ActionType = apps.get_model('geowebapp', 'CV_ActionType')

    ActionBy = apps.get_model('geowebapp', 'ActionBy')
    FeatureActions = apps.get_model('geowebapp', 'FeatureActions')

    sampling_feature_type_cv = CV_SamplingFeatureType.objects.filter(
        term="fieldArea").first()
    elevation_datum_cv = CV_ElevationDatum.objects.filter(term="MSL").first()

    action_type_cv = CV_ActionType.objects.filter(
        term="genericNonObservation").first()
    method_type_cv = CV_MethodType.objects.filter(
        term="genericNonObservation").first()
    organization = Organizations.objects.filter(organizationcode='WSU').first()
    affiliation = Affiliations.objects.filter(
        primaryemail='dave.brown@wsu.edu').first()

    relationship_type_cv = CV_RelationshipType.objects.filter(
        term='isPartOf').first()
    farm_feature = SamplingFeatures.objects.filter(
        samplingfeaturecode='CookAgronomyFarm').first()

    for file_path in files_path:
        full_file_path = Path(__file__).resolve().parent.parent / file_path
        field_data = gpd.read_file(str(full_file_path))
        field_data = field_data.to_crs(3857)
        wkt = shapely.to_wkt(
            field_data.geometry.values[0], trim=False, output_dimension=2)

        field_code = field_data.Field.values[0]
        # to convert the Geometry type to match the CV in the ODM
        geotype = field_data.geom_type
        samplingfeaturegeotypecv = CV_SamplingFeatureGeoType.objects.filter(
            term=geotype[0].lower() + geotype[1:]
        ).first()
        field_feature = SamplingFeatures(
            samplingfeatureuuid=str(uuid.uuid4()),
            samplingfeaturename=f"Field {field_code}",
            samplingfeaturetypecv=sampling_feature_type_cv,
            samplingfeaturecode=f"Field{field_code}",
            samplingfeaturedescription='A field of the Cook Agronomy Farm',
            featuregeometry=wkt,
            featuregeometrywkt=wkt,
            samplingfeaturegeotypecv=samplingfeaturegeotypecv,
            elevation_m=-9999,
            elevationdatumcv=elevation_datum_cv,
        )
        field_feature.save()

        related_feature = RelatedFeatures(
            samplingfeatureid=field_feature,
            relatedfeatureid=farm_feature,
            relationshiptypecv=relationship_type_cv
        )
        related_feature.save()

        method = Methods(
            methodtypecv=method_type_cv,
            methodcode=str(uuid.uuid4()),
            methodname='Not applicable',
            methoddescription=None,
            methodlink=None,
            organizationid=organization
        )
        method.save()

        action = Actions(
            begindatetime=timezone.make_aware(datetime(2007, 1, 1, 0, 0, 0)),
            begindatetimeutcoffset=-4,
            actiontypecv=action_type_cv,
            actiondescription='',
            methodid=method
        )
        action.save()

        featureaction = FeatureActions(
            actionid=action,
            samplingfeatureid=field_feature
        )
        featureaction.save()

        action_by = ActionBy(
            isactionlead=False,
            # roledescription='', #no role for this specific sampling feature
            actionid=action,
            affiliationid=affiliation
        )
        action_by.save()


class Migration(migrations.Migration):

    dependencies = [
        ("geowebapp", "0004_auto_20250612_1522"),
    ]

    operations = [
        migrations.RunPython(load_fields_polygon_data)
    ]
