# Generated by Django 5.2 on 2025-06-12 15:30

import uuid
from datetime import datetime
from django.utils import timezone
from pathlib import Path

from django.db import migrations
from django.contrib.gis.geos import GEOSGeometry

import geopandas as gpd
import shapely


def load_sensors_location_data(apps, schema_editor):
    file_path = 'static/data/farming/spatial/SensorsLocation.geojson'
    full_file_path = Path(__file__).resolve().parent.parent / file_path

    sensors_location = gpd.read_file(str(full_file_path))
    sensors_location = sensors_location.to_crs(3857)

    # Les tables requises pour l'insertion des données spatiales
    SamplingFeatures = apps.get_model('geowebapp', 'SamplingFeatures')
    CV_SamplingFeatureType = apps.get_model(
        'geowebapp', 'CV_SamplingFeatureType')
    CV_SamplingFeatureGeoType = apps.get_model(
        'geowebapp', 'CV_SamplingFeatureGeoType')
    RelatedFeatures = apps.get_model('geowebapp', 'RelatedFeatures')
    CV_RelationshipType = apps.get_model('geowebapp', 'CV_RelationshipType')

    CV_ElevationDatum = apps.get_model('geowebapp', 'CV_ElevationDatum')

    Organizations = apps.get_model('geowebapp', 'Organizations')
    Affiliations = apps.get_model('geowebapp', 'Affiliations')

    Methods = apps.get_model('geowebapp', 'Methods')
    CV_MethodType = apps.get_model('geowebapp', 'CV_MethodType')

    Actions = apps.get_model('geowebapp', 'Actions')
    CV_ActionType = apps.get_model('geowebapp', 'CV_ActionType')

    ActionBy = apps.get_model('geowebapp', 'ActionBy')
    FeatureActions = apps.get_model('geowebapp', 'FeatureActions')

    sampling_feature_type_cv = CV_SamplingFeatureType.objects.filter(
        term="site").first()
    elevation_datum_cv = CV_ElevationDatum.objects.filter(term="MSL").first()

    action_type_cv = CV_ActionType.objects.filter(
        term="instrumentDeployment").first()
    method_type_cv = CV_MethodType.objects.filter(
        term="instrumentDeployment").first()
    organization = Organizations.objects.filter(organizationcode='WSU').first()
    affiliation = Affiliations.objects.filter(
        primaryemail='dave.brown@wsu.edu').first()

    relationship_type_cv = CV_RelationshipType.objects.filter(
        term='isLocatedAt').first()

    for _, sensor in sensors_location.iterrows():
        parcel_code = sensor.Strip
        field_code = sensor.Field
        # to convert the Geometry type to match the CV in the ODM
      
        geotype = sensor.geometry.type[0]
        samplingfeaturegeotypecv = CV_SamplingFeatureGeoType.objects.filter(
            term=geotype[0].lower() + geotype[1:]
        ).first()

        wkt = shapely.to_wkt(
            list(sensor.values)[-1], trim=False, output_dimension=2)
        
        parcel_feature = SamplingFeatures(
            samplingfeatureuuid=str(uuid.uuid4()),
            samplingfeaturename=f"Sensor deployed in Parcel {parcel_code} of field {field_code}",
            samplingfeaturetypecv=sampling_feature_type_cv,
            samplingfeaturecode=sensor.Location,  # premiere colonne du fichier de données
            samplingfeaturedescription=f"A sensor deployed in Parcel {parcel_code} of field {field_code}",
            featuregeometry=wkt,
            featuregeometrywkt=wkt,
            samplingfeaturegeotypecv=samplingfeaturegeotypecv,
            elevation_m=-9999,
            elevationdatumcv=elevation_datum_cv,
        )
        parcel_feature.save()

        related_feature = SamplingFeatures.objects.filter(
            samplingfeaturecode=f"Parcel{parcel_code}_Field{field_code}").first()

        related_feature = RelatedFeatures(
            samplingfeatureid=parcel_feature,
            relatedfeatureid=related_feature,
            relationshiptypecv=relationship_type_cv
        )
        related_feature.save()

        method = Methods(
            methodtypecv=method_type_cv,
            methodcode=str(uuid.uuid4()),
            methodname='Not applicable',
            methoddescription=None,
            methodlink=None,
            organizationid=organization
        )
        method.save()

        action = Actions(
            begindatetime=timezone.make_aware(datetime(2007, 1, 1, 0, 0, 0)),
            begindatetimeutcoffset=-4,
            actiontypecv=action_type_cv,
            actiondescription='',
            methodid=method
        )
        action.save()

        featureaction = FeatureActions(
            actionid=action,
            samplingfeatureid=parcel_feature
        )
        featureaction.save()

        action_by = ActionBy(
            isactionlead=False,
            # roledescription='', #no role for this specific sampling feature
            actionid=action,
            affiliationid=affiliation
        )
        action_by.save()


class Migration(migrations.Migration):

    dependencies = [
        ("geowebapp", "0006_auto_20250612_1522"),
    ]

    operations = [
        migrations.RunPython(load_sensors_location_data)
    ]
